# Generated by Django 4.0.3 on 2022-04-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locate', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=200)),
                ('ttpe', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('elevation_ft', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('iso_country', models.CharField(max_length=200)),
                ('iso_region', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('gps_code', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=200)),
                ('local_code', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('sesso', models.CharField(max_length=20)),
                ('luogo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_andate', models.DateField()),
                ('date_ritorno', models.DateField()),
                ('neonati', models.SmallIntegerField()),
                ('bambini', models.SmallIntegerField()),
                ('adulti', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assistente', models.CharField(max_length=100)),
                ('Pilota', models.CharField(max_length=100)),
                ('ass_Pilota', models.CharField(max_length=100)),
                ('Hostess_di_volo', models.CharField(max_length=100)),
                ('Hostess_di_terra', models.CharField(max_length=100)),
                ('ass_airport', models.CharField(max_length=100)),
                ('Addetto_di_Scalo', models.CharField(max_length=100)),
                ('Steward_terra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_passeggeri', models.IntegerField()),
                ('Aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft')),
            ],
        ),
    ]
