# Generated by Django 4.0.3 on 2022-05-01 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locate', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('tot_posti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=200)),
                ('ttpe', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('elevation_ft', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('iso_country', models.CharField(max_length=200)),
                ('iso_region', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('gps_code', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=200)),
                ('local_code', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assistente', models.CharField(max_length=100)),
                ('Pilota', models.CharField(max_length=100)),
                ('ass_Pilota', models.CharField(max_length=100)),
                ('Hostess_di_volo', models.CharField(max_length=100)),
                ('Hostess_di_terra', models.CharField(max_length=100)),
                ('ass_airport', models.CharField(max_length=100)),
                ('Addetto_di_Scalo', models.CharField(max_length=100)),
                ('Steward_terra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_andate', models.DateField()),
                ('date_ritorno', models.DateField()),
                ('neonati', models.SmallIntegerField()),
                ('bambini', models.SmallIntegerField()),
                ('adulti', models.SmallIntegerField()),
                ('andata_e_o_ritorno', models.CharField(max_length=50)),
                ('arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='sito_gestione_voli.airport')),
                ('partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='sito_gestione_voli.airport')),
            ],
        ),
        migrations.CreateModel(
            name='posti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_del_posto', models.CharField(choices=[('prima classe libero', 'prima classe libero'), ('prima classe occupato', 'prima classe occupato'), ('seconda classe libero', 'seconda classe libero'), ('seconda classe occupato', 'seconda classe occupato')], default='prima classe libero', max_length=40)),
                ('tot_posti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('sesso', models.CharField(max_length=20)),
                ('luogo', models.CharField(max_length=200)),
                ('ruolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.ruolo')),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_passeggeri', models.IntegerField()),
                ('date_andata', models.DateField(default=django.utils.timezone.now)),
                ('date_ritorno', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft')),
                ('arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine', to='sito_gestione_voli.airport')),
                ('partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inizio', to='sito_gestione_voli.airport')),
            ],
        ),
        migrations.CreateModel(
            name='andata_o_andata_e_ritorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andata_e_o_ritonro', models.CharField(choices=[('Solo andata', 'Solo andata'), ('andata e ritorno', 'andata e ritorno')], default='Solo andata', max_length=25)),
                ('andata_e_o_ritorno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.prenotazione')),
            ],
        ),
    ]
