# Generated by Django 4.0.3 on 2022-04-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='andata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inizio', to='sito_gestione_voli.airport'),
        ),
        migrations.AddField(
            model_name='fly',
            name='ritorno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine', to='sito_gestione_voli.airport'),
        ),
        migrations.AddField(
            model_name='personale',
            name='ruolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.ruolo'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='andata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='sito_gestione_voli.airport'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='ritorno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='sito_gestione_voli.airport'),
        ),
    ]
