# Generated by Django 4.0.3 on 2022-05-01 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='date_andate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='date_ritorno',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
