# Generated by Django 4.0.3 on 2022-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0002_alter_prenotazione_date_andate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='date_andate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='date_ritorno',
            field=models.DateField(),
        ),
    ]
