# Generated by Django 4.0.3 on 2022-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0002_fly_andata_fly_ritorno_personale_ruolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
