# Generated by Django 4.0.3 on 2022-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0003_aircraft_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='year_in_school',
            field=models.CharField(choices=[('PL', 'prima_classe_libero'), ('PO', 'prima_classe_occupato'), ('SL', 'seconda_classe_libero'), ('SO', 'seconda_classe_occupato')], default='PL', max_length=2),
        ),
    ]
