# Generated by Django 4.0.3 on 2022-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0003_alter_prenotazione_date_andate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='andata_e_o_ritorno',
            field=models.CharField(choices=[('prima classe libero', 'prima classe libero'), ('prima classe occupato', 'prima classe occupato'), ('seconda classe libero', 'seconda classe libero'), ('seconda classe occupato', 'seconda classe occupato')], default='prima classe libero', max_length=40),
        ),
        migrations.DeleteModel(
            name='andata_o_andata_e_ritorno',
        ),
    ]
