# Generated by Django 4.0.4 on 2022-05-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0004_alter_prenotazione_andata_e_o_ritorno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personale',
            name='luogo',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tot_posti',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='fly',
            name='tot_passeggeri',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='personale',
            name='ruolo',
            field=models.IntegerField(choices=[(1, 'Assistente'), (2, 'Pilota'), (3, 'Assistente Pilota'), (4, 'puttana volante'), (5, 'puttana di terra'), (6, 'assistente di volo'), (7, 'Adetto di Scalo'), (8, 'Steward terra')], default=1),
        ),
        migrations.AlterField(
            model_name='posti',
            name='tot_posti',
            field=models.ForeignKey(default=60, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft'),
        ),
        migrations.DeleteModel(
            name='Prenotazione',
        ),
        migrations.DeleteModel(
            name='Ruolo',
        ),
    ]
