# Generated by Django 4.0.3 on 2022-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0004_alter_aircraft_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='year_in_school',
            field=models.CharField(choices=[('PL', 'prima classe libero'), ('PO', 'prima classe occupato'), ('SL', 'seconda classe libero'), ('SO', 'seconda classe occupato')], default='PL', max_length=2),
        ),
    ]
