# Generated by Django 4.0.3 on 2022-04-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0005_alter_aircraft_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='year_in_school',
            new_name='stato_del_posto',
        ),
    ]
