# Generated by Django 4.0.4 on 2022-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0005_remove_personale_luogo_alter_aircraft_tot_posti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personale',
            name='ruolo',
            field=models.IntegerField(choices=[(1, 'Assistente'), (2, 'Pilota'), (3, 'Assistente Pilota'), (4, 'puttana volante'), (5, 'puttana di terra'), (6, 'assistente di volo'), (7, 'Adetto di Scalo'), (8, 'Steward terra')], default=1),
        ),
    ]
