# Generated by Django 4.0.3 on 2022-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0006_rename_year_in_school_aircraft_stato_del_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='posti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_del_posto', models.CharField(choices=[('PL', 'prima classe libero'), ('PO', 'prima classe occupato'), ('SL', 'seconda classe libero'), ('SO', 'seconda classe occupato')], default='PL', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='stato_del_posto',
        ),
    ]
