# Generated by Django 4.0.4 on 2022-05-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0006_alter_personale_ruolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posti',
            old_name='tot_posti',
            new_name='idAircraft',
        ),
    ]
