# Generated by Django 4.0.4 on 2022-05-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0007_rename_tot_posti_posti_idaircraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posti',
        ),
    ]
