# Generated by Django 4.0.3 on 2022-04-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0008_aircraft_tot_posti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='tot_posti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sito_gestione_voli.posti'),
        ),
    ]
