# Generated by Django 4.0.4 on 2022-05-05 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0008_delete_posti'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_andate', models.DateField()),
                ('date_ritorno', models.DateField()),
                ('neonati', models.SmallIntegerField()),
                ('bambini', models.SmallIntegerField()),
                ('adulti', models.SmallIntegerField()),
                ('andata_e_o_ritorno', models.CharField(max_length=50)),
                ('arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_end', to='sito_gestione_voli.airport')),
                ('partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_start', to='sito_gestione_voli.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_andate', models.DateField()),
                ('date_ritorno', models.DateField()),
                ('neonati', models.SmallIntegerField()),
                ('bambini', models.SmallIntegerField()),
                ('adulti', models.SmallIntegerField()),
                ('andata_e_o_ritorno', models.CharField(max_length=50)),
                ('arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='sito_gestione_voli.airport')),
                ('partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='sito_gestione_voli.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_passeggeri', models.IntegerField(default=60)),
                ('date_andata', models.DateField(default=django.utils.timezone.now)),
                ('date_ritorno', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft')),
                ('arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_fine', to='sito_gestione_voli.airport')),
                ('partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_inizio', to='sito_gestione_voli.airport')),
            ],
        ),
    ]
