# Generated by Django 4.0.3 on 2022-04-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0009_alter_aircraft_tot_posti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='tot_posti',
        ),
        migrations.AddField(
            model_name='posti',
            name='tot_posti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft'),
        ),
    ]
