# Generated by Django 4.0.4 on 2022-05-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0009_prenotazionehistory_prenotazione_flyhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='date_andate',
            new_name='data_andata',
        ),
        migrations.RenameField(
            model_name='prenotazione',
            old_name='date_ritorno',
            new_name='data_ritorno',
        ),
    ]
