# Generated by Django 4.0.3 on 2022-04-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0010_remove_aircraft_tot_posti_posti_tot_posti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posti',
            name='stato_del_posto',
            field=models.CharField(choices=[('prima classe libero', 'prima classe libero'), ('prima classe occupato', 'prima classe occupato'), ('seconda classe libero', 'seconda classe libero'), ('seconda classe occupato', 'seconda classe occupato')], default='prima classe libero', max_length=40),
        ),
    ]
